name: evolduo app

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@5
        with:
          cli: 1.11.1.1113
      - name: Run tests
        run: clojure -X:test
