name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@5.0
        with:
          cli: 1.11.1.1113

      - name: Run tests
        run: clojure -X:test

      - name: Build uberjar
        run: clojure -T:build uber

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@4
        with:
          name: kongeor/evolduo-app
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
